name: Docker

on:
  push:
    branches: [ "20.04" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build -t rossedlin/docker-ubuntu:20.04 .

      - uses: actions/checkout@v3
      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ vars.DOCKER_HUB_USER }} --password-stdin

      - uses: actions/checkout@v3
      - name: Push Image to Docker
        run: docker push rossedlin/docker-ubuntu:20.04
